### ISSUE TITLE
Summary cannot handle Bard elements

### ISSUE THREAD

**Issue by le-martre** [mitydigital/statamic-feedamic#4]
Hello ! 

Just figure I'd mention it here but Bard elements make the "summary" function bug out because it's accessing the Bard value (an array) as a string.

I had to add some custom code at FeedEntry.php:66 to get it working, here is what I did (dirty but works) :
```php
// Hack to handle Bard elements
if(is_array($summary)) {
  $new_summary = '';

  foreach($summary as $section) {
    if(!empty($section['type']) && $section['type'] === 'text') {
      $new_summary = $section['text'];
      break;
    }
  }

  $summary = $new_summary;
}
```

Figured it might help other people, cheers ! And thanks for the great package

**Comment by martyf** [comment]
Thanks for reporting this @MartinVandersteen - in a recent project I needed to process a bard field (totally different purpose) and have something similar, but also that works for custom sets. 

Has me thinking though whether its worth trying to find a way to also make this extensible so that it can run a bare-bones text process (like you've provided), and one that can also be extended app-by-app that can process explicitly defined sets within the Bard config. 

Maybe that's a bigger one than to tackle now but could be useful to give other devs the option to easily hook in to the summary creation with their own Bard sets.

I'll at least get this issue resolved with this text-only approach, but did you have any thoughts, ideas, considerations, concerns about being able to extend the behaviour too? Is this something that would be useful?

**Comment by martyf** [comment]
Righto so I have just published a new version that adds the logic in.

The bigger one for discussion is about how to process custom sets.

If it were just a single set, with a number of fields, it could have either a process class that dictates what content fields to get (and how to process them), but gets trickier then if you have a bard block within a set. And starts going down the more slippery slope towards the idea of literally rendering all the content in a dummy file (including set markup) and using that.

This bigger one I'd definitely like to discuss more to ensure whatever gets done works well, and gives other devs enough flexibility.

**Comment by tdwesten** [comment]
With #25, it will be possible to write your own FeedEntry model and implement it.

**Comment by martyf** [comment]
This is correct - with 2.4.0 you can write your own `FeedEntry` model (and thanks to @tdwesten for the initial `FeedEntry` model PR).

Your own model must implement the `FeedamicEntry` interface.

Given Bard sets are so specific to _your_ site (and can vary from _my_ site or _another_ site), there has previously not been a way to handle this generically for everyone. But with your own `FeedEntry` model, you can write your own logic to output your site's Bard sets.

You'll need to refer to the docs:
https://docs.mity.com.au/feedamic/interface
